### ISSUE TITLE
L'obligation de parité bloque les votes

### ISSUE THREAD

**Issue by Goutte** [m6r/nlp#7]
C'est tellement gros que vous être probablement au courant, mais il est impossible de voter pour les postes "genrés", comme https://vote.m6r.fr/polls/election/41/vote car le système requiert d'avoir sélectionné autant d'hommes que de femmes, pour un poste où il n'y a que des femmes car le poste n'est que pour les femmes (voir le lien).

**Comment by sdm94** [comment]
Comme le dit vivigatt au jourd'hui : 
"Exactement pareil ! Je croyais ne pas pouvoir voter. Mais en sélectionnant le poste déjà pourvu, ça marche. L'ergonomie est néanmoins très discutable : puisque le poste est déjà pourvu, il faut qu'il ne soit pas proposé et automatiquement sélectionné.
Les outils numériques sont une chance, mais il faut qu'ils soient adaptés... L'ergonomie est (très) importante."
